import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import { copyFileSync, existsSync, mkdirSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const vaultOutDir = join(__dirname, "../../../.obsidian/plugins/speed-reader-ai");
const releaseOutDir = __dirname;

const prod = process.argv[2] === "production";
const outDir =
	!prod || process.env.SPEED_READER_OUT === "vault" ? vaultOutDir : releaseOutDir;

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit https://github.com/yadubhushan/obsidian-AI-smart-speed-reader-ai
*/
`;

function copyFileIfMissing(src, dest) {
	mkdirSync(dirname(dest), { recursive: true });
	if (!existsSync(dest)) {
		copyFileSync(src, dest);
	}
}

function copyPromptsDirIfMissing(srcDir, destDir) {
	if (!existsSync(srcDir)) {
		return;
	}
	for (const name of readdirSync(srcDir)) {
		if (!name.endsWith(".txt")) {
			continue;
		}
		copyFileIfMissing(join(srcDir, name), join(destDir, name));
	}
}

function copyAssets() {
	mkdirSync(outDir, { recursive: true });
	// Bundle artifacts only — never delete or overwrite plugin `data/` (settings cache, read-cache, user config).
	copyFileSync(join(__dirname, "manifest.json"), join(outDir, "manifest.json"));
	copyFileSync(join(__dirname, "styles.css"), join(outDir, "styles.css"));
	copyFileIfMissing(
		join(__dirname, "config/llm-models.json"),
		join(outDir, "data/llm-models.json"),
	);
	copyPromptsDirIfMissing(
		join(__dirname, "config/prompts"),
		join(outDir, "data/prompts"),
	);
}

const buildOptions = {
	banner: {
		js: banner,
	},
	entryPoints: [join(__dirname, "src/main.ts")],
	loader: {
		".txt": "text",
	},
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		"child_process",
		"node:child_process",
		"node:fs",
		"node:path",
		...builtinModules,
	],
	format: "cjs",
	target: "es2018",
	platform: "browser",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: join(outDir, "main.js"),
	minify: prod,
};

if (prod) {
	mkdirSync(outDir, { recursive: true });
	await esbuild.build(buildOptions);
	copyAssets();
} else {
	const ctx = await esbuild.context({
		...buildOptions,
		plugins: [
			{
				name: "copy-static-assets",
				setup(build) {
					build.onEnd((result) => {
						if (result.errors.length === 0) copyAssets();
					});
				},
			},
		],
	});
	await ctx.rebuild();
	await ctx.watch();
}
